# Use the official Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install -r requirements.txt

RUN python -m spacy download en_core_web_sm

# Copy the application code to the working directory
COPY . .

# Expose the port on which the application will run
EXPOSE 5000

ENV FLASK_APP=app_flask.py

# Run the FastAPI application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]