# Use the official Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install -r requirements.txt

RUN python -m spacy download en_core_web_sm

# Copy the application code to the working directory
COPY . .

# Expose the port on which the application will run
EXPOSE 8501


# Run the Streamlit application
CMD ["streamlit", "run", "app_streamlit.py", "--server.port", "8501", "--server.headless", "true", "--server.enableCORS", "false"]